version: "3.7"

services:

  pandemic:
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    build: .
    environment:
      - PORT=${PORT}
      - VIRTUAL_PORT=${PORT}
      - VIRTUAL_HOST=${CONTAINER_NAME}.jimhendy.com
      - LETSENCRYPT_HOST=${CONTAINER_NAME}.jimhendy.com
    networks: 
      - reverse-proxy-net

networks:
  reverse-proxy-net:
    external: true