version: "3.7"

services:

  pandemic:
    container_name: pandemic
    restart: unless-stopped
    build: .
    environment:
      - PORT=${PORT}
      - VIRTUAL_PORT=${PORT}
      - VIRTUAL_HOST=pandemic.jimhendy.com
      - LETSENCRYPT_HOST=pandemic.jimhendy.com
    networks: 
      - net
    ports:
      - ${PORT}:${PORT}

networks:
  net:
    external: true